[[on_place_order]]
  function = "for_each"
  loop = "$$_order_items as oi"
  [on_place_order.for_each]
    before_iteration = [
      "%%_set(all_success,true)"
    ]
    each_iteration = [
      "%%_set(result,%%_make_external_request($$_oi))",
      "%%_if($$_result,%%_custom_function(handle_success,$$_result),%%_set(all_success,false))"
    ]
    break_iteration_if = "%%_negate(%%_if($$_all_success))"
