[meta]
version='2'

# Hooks are defined in the Database
# > implements:jsonb
# implements: ['on_place_order', 'on_update_order']

# condition_1 can be whatever you want it to be, it
# just needs to be unique
[hooks.on_place_order.condition_1.when]
"order.segment_code"="silver"

[hooks.on_place_order.condition_1.then]

[hooks.on_place_order.condition_2.when]
"order.segment_code"="gold"

[hooks.on_place_order.condition_2.then]
