[meta]
version='2'
arguments=["segment"]

[condition_1.when]
  segment="silver"
[condition_1.then]
  function="make_external_request"
  reference="preflight_silver"
  url="https://pointsbank.com/preflight"
  body={
     
  }
  
[callbacks]  
  [preflight_silver.success_when] 
  [preflight_silver.failure_when] 
  [preflight_silver.success] 
  [preflight_silver.failure] 
