#[[on_place_order]]
#  method = "for_each"
#  loop = "$$_order_items as oi"
#  [on_place_order.before]
#    functions = [
#      "%%_puts(------------------------)"
#    ]
#  [on_place_order.for_each]
#    before_iteration = [
#      "%%_set(all_success,true)"
#    ]
#    each_iteration = [
#      "%%_set(successful_order_items,%%_blank_array())",
#      "%%_set(result,%%_make_external_request($$_oi))",
#      "%%_if($$_result,%%_custom_function(handle_success,$$_result,$$_oi),%%_set(all_success,false))"
#    ]
#    break_iteration_if = "%%_negate(%%_if($$_all_success))"
#  [on_place_order.finally]
#    functions = [
#      "%%_puts(------------------------)"
#    ]

[[on_place_order]]
  run_if = "%%_eql(%%_count($$_order_items),5)"
  method = "for_each"
  loop = "$$_order_items as oi"
  [on_place_order.for_each]
    before_iteration = [
      "%%_set(all_success,true)"
    ]
    each_iteration = [
      "%%_set(successful_order_items,%%_blank_array())",
      "%%_set(result,%%_make_external_request($$_oi))",
      "%%_if($$_result,%%_custom_function(handle_success,$$_result,$$_oi),%%_set(all_success,false))"
    ]
    next_if = "%%_or(%%_eql($$_oi,2),%%_eql($$_oi,3))" 
    break_iteration_if = "%%_negate(%%_if($$_all_success))"
  [on_place_order.finally]
    functions = [
      "%%_puts($$_order_body.password)",
      "%%_for_each($$_successful_order_items,%%_custom_function(cancel_order_item),each_order_item)"
    ]
    

[custom_functions]
  [custom_functions.handle_success]
    arguments = [
      "result_from_success",
      "order_item"
    ]
    functions = [
      "%%_array_push($$_successful_order_items,%%_concat('this ',$$_order_item))",
      "%%_puts(%%_concat('this was our response: ',$$_result_from_success))"
    ]
  [custom_functions.cancel_order_item]
    arguments = [ ]
    functions = [
      "%%_puts($$_each_order_item)"
    ]

[configuration]
[configuration.order_body]
password = "123abc"
